language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - phpenv rehash

install:
  composer install

script:
  - ln -s `pwd` vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PHPCompatibility
  - phpunit --configuration phpunit.xml